{{- if eq .Values.kind "DaemonSet"}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prox
  annotations:
    k8s.v1.cni.cncf.io/networks: "{{- join "\",\"" .Values.extraInterfaces }}"
spec:
  selector:
    matchLabels:
      app: prox
  template:
    metadata:
      labels:
        app: prox
    spec:
      containers:
      - name: prox
        image: opnfv/rapid:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      nodeSelector:
        {{- .Values.nodeSelector.matchLables | toYaml | nindent 12 }}
{{- end }}
