apiVersion: v1
kind: Pod
metadata:
  name: vineperf
  labels:
    app: vineperf
spec:
  containers:
  - name: vineperf-container
    image: vsperf/vineperf:lakelse
    ports:
    - containerPort: 22
    resources:
      requests:
        cpu: "2000m"
        memory: "2000Mi"
      limits:
        cpu: "2000m"
        memory: "2000Mi"

---
#
# Service for exposing port outside of the cluster
#
apiVersion: v1
kind: Service
metadata:
  name: vineperf
  labels:
    app: vineperf
spec:
 type: NodePort                      # service type (exposing a port outside of the cluster)
 selector:
    app: vineperf
 ports:
    - nodePort: 32323                # port exposed by service
      port: 22                       # port associated with the service
      protocol: TCP                  # network protocol
      targetPort: 22
