---
- hosts:
    - 127.0.0.1
  roles:
      - role: collivier.xtesting
        project: vsperf
        repo: 127.0.0.1
        dport: 5000
        gerrit:
        suites:
            - container: phy2phy_tput
              tests:
                  - phy2phy_tput
