{{- if eq .Values.kind "Deployment"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpmd
  annotations:
    k8s.v1.cni.cncf.io/networks: "{{- join "\",\"" .Values.extraInterfaces | toYaml | nindent 8}}"
spec:
  selector:
    matchLabels:
      app: testpmd
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: testpmd
    spec:
      containers:
      - name: testpmd
        image: vsperf/dpdkfwd:lakelse
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      nodeSelector: 
        {{- .Values.nodeSelector.matchLables | toYaml | nindent 12 }}
{{- end }}