# Copyright 2020 Adarsh yadav, Aditya Srivastava
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
#Worker

- name: Copying token to worker nodes
  copy: src={{ token_file }} dest=join_token

- name: Joining worker nodes with kubernetes master
  shell: |
   kubeadm reset -f
   cat join_token | tail -1 > out.sh
   sh out.sh
