apiVersion: v1
kind: Pod
metadata:
  name: afxdp-l2fwd                              # Pod name
  annotations:
    k8s.v1.cni.cncf.io/networks: afxdp-east-network, afxdp-west-network # List of networks to attach to this pod
spec:
  containers:
  - name: afxdp
    image: dpdk-app-centos
    imagePullPolicy: Never
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
      capabilities:
        add: ["CAP_SYS_ADMIN"]
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        cpu: "6000m"
        afxdp/eastPool: '1'                      
        afxdp/westPool: '1'                      
      limits:                                  
        cpu: "6000m"
        hugepages-1Gi: 2Gi
        afxdp/eastPool: '1'                      
        afxdp/westPool: '1'                      
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages  
