apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudstress-deployment
spec:
  selector:
    matchLabels:
      app: cloudstress
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cloudstress
    spec:
      containers:
      - name: cloudstress
        image: vsperf/autocloudstress:thoth
        resources:
          requests:
            cpu: "2000m"
            memory: "2000Mi"
          limits:
            cpu: "2000m"
            memory: "2000Mi"
