# Copyright 2020 Aditya Srivastava.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  labels:
    adi10hero.monitoring: alertmanager1
    app: alertmanager1
  name: alertmanager1
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /
    prometheus.io/port: '8080'

spec:
  selector:
    app: alertmanager1
    adi10hero.monitoring: alertmanager1
  type: NodePort
  ports:
  - name: "9093"
    port: 9093
    targetPort: 9093
    nodePort: 30931
  - name: "6783"
    port: 6783
    targetPort: 6783
    nodePort: 30678

