{{- if eq .Values.kind "DaemonSet"}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: trex
  annotations:
    k8s.v1.cni.cncf.io/networks: "{{- join "\",\"" .Values.extraInterfaces }}"
spec:
  selector:
    matchLabels:
      app: trex
  template:
    metadata:
      labels:
        app: trex
    spec:
      containers:
      - name: trex
        image: vsperf/trex:lakelse
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      nodeSelector: 
        {{- .Values.nodeSelector.matchLables | toYaml | nindent 12 }}
{{- end }}