# Copyright 2020 Adarsh yadav
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master-vm1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: log-vm1-master
  nfs:
    server: 10.10.120.211
    path: "/srv/nfs/master"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-vm1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: log-vm1-data
  nfs:
    server: 10.10.120.211
    path: "/srv/nfs/data"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master-vm2
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: log-vm2-master
  nfs:
    server: 10.10.120.203
    path: "/srv/nfs/master"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-vm2
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: log-vm2-data
  nfs:
    server: 10.10.120.203
    path: "/srv/nfs/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master-vm3
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: log-vm3-master
  nfs:
    server: 10.10.120.204
    path: "/srv/nfs/master"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-vm3
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: log-vm3-data
  nfs:
    server: 10.10.120.204
    path: "/srv/nfs/data"
