- port_limit    : 2         
  version       : 2
  interfaces    : ["81:00.0", "81:00.1"]   # list of the interfaces to bind # node 4
  port_bandwidth_gb : 10 #10G nics
  port_info       :  # set eth mac addr
          - dest_mac        :   "3c:fd:fe:b4:41:09"  # port 0
            src_mac         :   "3c:fd:fe:b4:41:08"
          - dest_mac        :   "3c:fd:fe:b4:41:08"  # port 1
            src_mac         :   "3c:fd:fe:b4:41:09"
  platform :
        master_thread_id  : 17
        latency_thread_id : 16
        dual_if   :
             - socket   : 1
               threads  : [22,23,24,25,26,27]
             - socket   : 0
               threads  : [10,11,12,13,14,15]



