apiVersion: v1
kind: Pod
metadata:
  name: userspace-vpp-pod2
  annotations:
    k8s.v1.cni.cncf.io/networks: userspace-vpp-net, userspace-vpp-net
spec:
  containers:
  - name: vpp-vhost
    image: newdpdk-app-centos:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podinfo
      readOnly: false
    - mountPath: /var/lib/cni/usrspcni/
      name: shared-dir
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        cpu: "6000m"
        hugepages-1Gi: 4Gi
      limits:
        cpu: "6000m"
        hugepages-1Gi: 4Gi
    command: ["sleep", "infinity"]
  nodeSelector:
    vswitch: ovs
  volumes:
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  - name: shared-dir
    hostPath:
      path: /var/lib/cni/usrspcni/data/
  - name: hugepage
    emptyDir:
      medium: HugePages
