---
- name: Drain master node
  shell: kubectl drain {{ansible_hostname}} --delete-local-data --force --ignore-daemonsets
    
- name: Delete master node
  shell: kubectl delete node {{ansible_hostname}}
   
- name: Kubeadm reset (master)
  shell: yes y | sudo kubeadm reset

- name: Delete /etc/cni/net.d/ (master)
  shell: sudo rm -rf /etc/cni/net.d/

- name: Delete $HOME/.kube/
  shell: rm -rf $HOME/.kube/ 
      
- name: Delete init log file
  shell: rm -rf {{ token_file }} 