---

- name: Clean kubevirt-ovs
  include: clear-kubevirt-ovs.yml

- name: Deploy ovs-cni-plugin
  k8s:
    state: present
    apply: yes
    definition: "{{ lookup('file', 'ovs-daemonset.yml') }}"


