---

- name: Clean Calico
  import_tasks: clear-calico.yaml

- name: Deploy Calico
  k8s:
    state: present
    apply: yes
    definition: '{{ item }}'
  with_items: '{{ lookup("url", "https://docs.projectcalico.org/manifests/calico.yaml", split_lines=False) | from_yaml_all | list }}'
  when: item is not none
