#
# cloned from https://github.com/nokia/danm/blob/v4.3.0/integration/bootstrap_networks/lightweight/flannel.yaml
#

apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: flannel
  namespace: kube-system
spec:
  NetworkID: flannel
  NetworkType: flannel